version: '3'
services:

  webserver:
    container_name: "addr_book_web_server"
    image: nginx:latest
    ports:
      - 80:80
      - 433:433
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html/
    links:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    container_name: "addr_book_php"
    build: docker/php-fpm
    environment:
      - TZ:"Europe/Rome"
    volumes:
      - ./:/var/www/html/
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - 9000:9000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge